---
- name: Deploy Matrix Synapse stack
  hosts: matrix
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: common
      tags: [common, hardening]
    - role: docker
      tags: [docker]
    - role: matrix
      tags: [matrix]
